//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disney.iDash.DataLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int CommandTimeout {
            get {
                return ((int)(this["CommandTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Provider=IBMDASQL.DataSource.1;Data Source=TDST.TDS.DISNEY.COM;Persist Security Info=False;Initial Catalog=TDST;Default Collection=*USRLIBL;Convert Date Time To Char=FALSE;Data Compression=True;Library List=QTEMP,TDSFILDSS2,TDSFILUKS,TDSHSTUKS,TDSDB2DSS,IPTSFILUKS,IPSAFILUKS,IPASFILUKS,IPWMFILUKS,IPTSITGUKY,IPTSITGEUY,IPTSITGDSY,IPTSQUAUKY,IPTSQUAEUY,IPTSQUADSY,IPTSMODUKY,IPTSMODEUY,IPTSMODDSY,IPTSPCH,IPTSPGM,IPTSUTL,IPSAPGM,DISCMDLIS,DISCMDLIY,TDSWWFILY;Naming Convention=1;Block Size=6000")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogSQL {
            get {
                return ((bool)(this["LogSQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DSIPWRAP")]
        public string DefaultWrapper {
            get {
                return ((string)(this["DefaultWrapper"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QGPL/QTXTSRCH")]
        public string DefaultJobQueue {
            get {
                return ((string)(this["DefaultJobQueue"]));
            }
        }
    }
}
