//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disney.iDash.SRR.BusinessLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disney.iDash.SRR.BusinessLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	DDPT as DeptId,
        ///	TRIM(DNAM) || &apos; (&apos; || DDPT || &apos;)&apos; AS DeptName
        ///FROM
        ///	IPDEPTS
        ///ORDER BY
        ///	DNAM.
        /// </summary>
        internal static string SQLDepartmentsSelect {
            get {
                return ResourceManager.GetString("SQLDepartmentsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	a.GDSTR AS StoreID, 
        ///	b.SNAM as StoreName,
        ///	GDCHGU as ChangedBy,
        ///	GDCHGD as ChangedDateTime
        ///FROM 
        ///	DSSRSGR a
        ///	JOIN IPSTORE b
        ///	ON a.GDSTR = b.SSTR
        ///WHERE 
        ///	GDDEPT=&lt;deptId&gt; AND GDGRADE=&apos;&lt;gradeId&gt;&apos;
        ///ORDER BY  
        ///	a.GDSTR
        ///.
        /// </summary>
        internal static string SQLDeptGradeStoresSelect {
            get {
                return ResourceManager.GetString("SQLDeptGradeStoresSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	&lt;item&gt; AS ITEM,
        ///	&lt;prefix&gt;CLS AS Class,
        ///	&lt;prefix&gt;VEN As Vendor,
        ///	&lt;prefix&gt;STY As Style,
        ///	&lt;prefix&gt;CLR As Colour,
        ///	&lt;prefix&gt;SIZ As Size,
        ///	&lt;prefix&gt;IDES As Description,
        ///	&lt;prefix&gt;MKT As Market,
        ///	&lt;prefix&gt;GRD As Grade,
        ///	&lt;prefix&gt;STRGRD as GradeDescription,
        ///	&lt;prefix&gt;STR As Store,
        ///	&lt;prefix&gt;SNAM As StoreName,
        ///
        ///	CASE 
        ///	WHEN &lt;prefix&gt;STRTYP = &apos;C&apos; THEN &apos;Online&apos; 
        ///	WHEN &lt;prefix&gt;STRTYP = &apos;B&apos; THEN &apos;B&amp;M&apos; 
        ///	ELSE &apos;Unknown&apos; END as StoreType,
        ///
        ///	CASE
        ///	WHEN &lt;prefix&gt;WBENCH =&apos;D&apos; THEN &apos;Daily&apos;
        ///	WHEN &lt;prefix&gt;WBE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLDetailedWorkbench {
            get {
                return ResourceManager.GetString("SQLDetailedWorkbench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	DCCLS As Class,
        ///	CASE 
        ///	WHEN DCWBENCH = &apos;D&apos; THEN &apos;Daily&apos;
        ///	WHEN DCWBENCH = &apos;W&apos; THEN &apos;Weekly&apos;
        ///	END AS Workbench,
        ///	CASE 
        ///	WHEN DCSTRTYP = &apos;C&apos; THEN &apos;Online&apos;
        ///	WHEN DCSTRTYP = &apos;B&apos; THEN &apos;B&amp;M&apos;
        ///	END As StoreType,
        ///	DCSLUL As SalesLW,
        ///	DCSLUT As SalesTW,
        ///	DCCSRS As CurrentROS,
        ///	DCSSOH As StockonHand,
        ///	DCSWOC As Smoothedstorecover,
        ///	DCALRT As Allocated,
        ///	DCINTS As Shipped,
        ///	DCCSSR As Totalstockrequired,
        ///	DCNSRQ As IdealAllocQty,
        ///	IGPRAQ As ProposedAllocQty,
        ///	DCSTOU As Outofstock
        ///FROM
        ///	DSSR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLFocusGroupsSelectClasses {
            get {
                return ResourceManager.GetString("SQLFocusGroupsSelectClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	SDSTR As Store,
        ///	SDSNAM As StoreName,
        ///	CASE 
        ///	WHEN SDWBENCH = &apos;D&apos; THEN &apos;Daily&apos;
        ///	WHEN SDWBENCH = &apos;W&apos; THEN &apos;Weekly&apos;
        ///	END AS Workbench,
        ///	CASE 
        ///	WHEN SDSTRTYP = &apos;C&apos; THEN &apos;Online&apos;
        ///	WHEN SDSTRTYP = &apos;B&apos; THEN &apos;B&amp;M&apos;
        ///	END As StoreType,
        ///	SDMKT As Market,
        ///	SDSLUL As SalesLW,
        ///	SDSLUT As SalesTW,
        ///	SDCSRS As CurrentROS,
        ///	SDSSOH As StockonHand,
        ///	SDSWOC As Smoothedstorecover,
        ///	SDINTA As Allocated,
        ///	SDINTS As Shipped,
        ///	SDCSSR As Totalstockrequired,
        ///	SDNSRQ As IdealAllocQty,
        ///	SDPRAQ As ProposedAll [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLFocusGroupsSelectStores {
            get {
                return ResourceManager.GetString("SQLFocusGroupsSelectStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	m.SRCLS As Class,
        ///	m.SRVEN As Vendor,
        ///	m.SRSTY As Style,
        ///	m.SRCLR As Colour,
        ///	m.SRSIZ As Size,
        ///	i.IDES As Description,
        ///	m.SRUPC as UPC,
        ///	m.SRSTR As Store,
        ///	s.SNAM As StoreName,
        ///	m.SRSTRTYP as StoreType,
        ///	m.SROROS As OpeningRateOfSale,
        ///	h.DMDQT as MinDispQty,
        ///	m.SRDEPT As Department,
        ///	m.SRFFCT As UpliftFactor,
        ///	m.SRCCO As CoverCutOff,
        ///	m.SRAFLG As AllocationFlag,
        ///	m.SRSFCT As SmoothingFactor,
        ///	repeat(&apos; &apos;, 128) as Error,
        ///	0 AS DeleteFlag
        ///FROM
        ///	DSSRDTL m
        ///	JOIN DSITHDR h
        ///	ON m.SRC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLItemDetailsSelect {
            get {
                return ResourceManager.GetString("SQLItemDetailsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	a.USDept as Id, 
        ///	a.USDept || &apos; - &apos; || d.DNAM as Description
        ///FROM
        ///	DSUSRDA a
        ///		LEFT JOIN IPDEPTS d
        ///		ON d.DDPT = a.USDEPT
        ///WHERE
        ///	&lt;whereClause&gt;
        ///ORDER BY 
        ///	a.USDept.
        /// </summary>
        internal static string SQLLookupDepartments {
            get {
                return ResourceManager.GetString("SQLLookupDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	PrCode as Id,
        ///	TRIM(PrDesc) || &apos; (&apos; || TRIM(PrCode) || &apos;)&apos; as Description
        ///FROM 
        ///	DSPROMO 
        ///WHERE
        ///	PrCode &lt;&gt; &apos;&apos;
        ///ORDER BY 
        ///	PrCode.
        /// </summary>
        internal static string SQLLookupEventCodes {
            get {
                return ResourceManager.GetString("SQLLookupEventCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT         ///	FMCode as Id,        ///	TRIM(FMDesc) || &apos; (&apos; || Trim(FMCode) || &apos;)&apos; as Description        ///FROM         ///	DSFAMLY         ///ORDER BY         ///	FMCode.
        /// </summary>
        internal static string SQLLookupFranchises {
            get {
                return ResourceManager.GetString("SQLLookupFranchises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	UUID As Id,
        ///	Trim(UNAM) || &apos; (&apos; || Trim(UUID) || &apos;)&apos;  As Username
        ///FROM
        ///	IPUSERS
        ///ORDER BY
        ///	UNAM.
        /// </summary>
        internal static string SQLLookupIPUsers {
            get {
                return ResourceManager.GetString("SQLLookupIPUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	i.CCLS as Id,
        ///	i.CLNM as Description
        ///FROM
        ///	IPCLASS i
        ///		JOIN DSCLASS d
        ///		ON i.CCLS = d.CCLS
        ///WHERE
        ///	d.CCODE=&apos;Y&apos;
        ///	AND &lt;whereClause&gt;
        ///ORDER BY
        ///	i.CCLS.
        /// </summary>
        internal static string SQLLookupItemClass {
            get {
                return ResourceManager.GetString("SQLLookupItemClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	VENID As Id,
        ///	VENNAM As Description
        ///FROM
        ///	DSSPVENP
        ///WHERE 
        ///	&lt;whereClause&gt;
        ///ORDER BY
        ///	VENID.
        /// </summary>
        internal static string SQLLookupItemVendors {
            get {
                return ResourceManager.GetString("SQLLookupItemVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	CSCODE as ID,
        ///	TRIM(CSDESC) || &apos; (&apos; || TRIM(CSCODE) || &apos;)&apos; As Description
        ///FROM
        ///	DSCNTAP
        ///ORDER BY
        ///	CSCSEQ.
        /// </summary>
        internal static string SQLLookupMarkets {
            get {
                return ResourceManager.GetString("SQLLookupMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	PatId as Id,
        ///	Trim(PatNam) || &apos; (&apos; || PatId || &apos;)&apos; As Description
        ///FROM
        ///	DSSRPAT
        ///ORDER BY
        ///	PatId.
        /// </summary>
        internal static string SQLLookupPatterns {
            get {
                return ResourceManager.GetString("SQLLookupPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	IUPD as Id,
        ///	TRIM(IDES) || &apos; (&apos; || TRIM(IUPD) || &apos;)&apos; as Description
        ///
        ///FROM
        ///	IPITHDRC
        ///ORDER BY
        ///	IDES.
        /// </summary>
        internal static string SQLLookupProducts {
            get {
                return ResourceManager.GetString("SQLLookupProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Promotion_Name as Id, 
        ///	TRIM(Description) || &apos; (&apos; || TRIM(PROMOTION_NAME) || &apos;)&apos; As Description
        ///FROM 
        ///	DSPROMST 
        ///WHERE
        ///	ENDDAT &gt; ((SELECT DATE(CURRENT_DATE) FROM SYSIBM/SYSDUMMY1) - 3 MONTHS)
        ///ORDER BY 
        ///	Promotion_Name.
        /// </summary>
        internal static string SQLLookupPromotions {
            get {
                return ResourceManager.GetString("SQLLookupPromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	SUBSTRING(SKEY, 2) as Id,
        ///	TRIM(SNAM) || &apos; (&apos; || TRIM(SUBSTRING(SKEY, 2)) || &apos;)&apos; AS Description,
        ///	TRIM(SNAM) AS AltDescription
        ///FROM
        ///	IPSTRTB
        ///WHERE
        ///	SKEY IN (SELECT ALSTGRP FROM DSALSTG)
        ///ORDER BY
        ///	SKEY.
        /// </summary>
        internal static string SQLLookupStoreGrades {
            get {
                return ResourceManager.GetString("SQLLookupStoreGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	SGPID as Id,
        ///	TRIM(SGPNAM) || &apos; (&apos; || TRIM(SGPID) || &apos;)&apos; AS Description
        ///FROM
        ///	DSSRSGP 
        ///ORDER BY
        ///	1.
        /// </summary>
        internal static string SQLLookupStoreGroups {
            get {
                return ResourceManager.GetString("SQLLookupStoreGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	SGSTR as Id,
        ///	TRIM(SGSNAM) || &apos; (&apos; || SGSTR || &apos;)&apos; As Description
        ///FROM
        ///	DSSRMSG3
        ///ORDER BY
        ///	SGSTR.
        /// </summary>
        internal static string SQLLookupStores {
            get {
                return ResourceManager.GetString("SQLLookupStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	s.SGSTR as Id,
        ///	TRIM(s.SGSNAM) || &apos; (&apos; || s.SGSTR || &apos;)&apos; As Description
        ///FROM
        ///	DSSRMSG3 s,
        ///	IPSTRTB sa
        ///WHERE 
        ///	sa.SKEY = &apos;USTW&apos;
        ///	AND SUBSTRING(sa.SARR, CAST(s.SGSTR AS INTEGER), 1) = &apos;1&apos;
        ///ORDER BY
        ///	s.SGSTR.
        /// </summary>
        internal static string SQLLookupStowawayStores {
            get {
                return ResourceManager.GetString("SQLLookupStowawayStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	IAJOB As LockedBy
        ///FROM
        ///	DSIALOK
        ///WHERE
        ///	IACLS = &lt;class&gt;
        ///	AND IAVEN = &lt;vendor&gt;
        ///	AND IASTY = &lt;style&gt;
        ///	AND IACLR = &lt;colour&gt;
        ///	AND IASIZ = &lt;size&gt;.
        /// </summary>
        internal static string SQLPackItemCheck {
            get {
                return ResourceManager.GetString("SQLPackItemCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM 
        ///	DSAPPALC 
        ///WHERE 
        ///	IAUPC = &apos;&lt;upc&gt;&apos;
        ///	AND IARLSUSR = &apos;&lt;userName&gt;&apos; 
        ///	AND IASTS=&apos;&apos;.
        /// </summary>
        internal static string SQLPackItemDeleteAllocations {
            get {
                return ResourceManager.GetString("SQLPackItemDeleteAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	s.SGMKT As Market,
        ///	s.SGSTR As Store,
        ///	s.SGSNAM as StoreName,
        ///	s.SGGRD as StoreGrade,
        ///	0 As ReleaseQty,
        ///	CASE WHEN i.IAUPC IS NULL THEN 0 ELSE 1 END as Allocated,
        ///	CASE WHEN z.IAUPC IS NULL THEN 0 ELSE 1 END as Locked
        ///FROM 
        ///	DSSRMSG s
        ///	LEFT JOIN DSAPPALC i
        ///		ON i.IADEPT=s.SGDEPT
        ///		AND i.IASTR=s.SGSTR 
        ///		AND i.IASTS = &apos;P&apos; 
        ///		AND i.IAORIGIN=&apos;S&apos; 
        ///		AND i.IACLS = &lt;class&gt;
        ///		AND i.IAVEN= &lt;vendor&gt;
        ///		AND i.IASTY= &lt;style&gt;
        ///		AND i.IACLR= &lt;colour&gt;
        ///		AND i.IASIZ= &lt;size&gt;
        ///
        ///	LEFT JOIN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLPackItemGetAllocations {
            get {
                return ResourceManager.GetString("SQLPackItemGetAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	RIGHT(&apos;0000&apos; || s.KCCL, 4) || &apos;-&apos; || RIGHT(&apos;00000&apos; || s.KCVN, 5) || &apos;-&apos; || RIGHT(&apos;0000&apos; || s.KCST, 4) || &apos;-&apos; || RIGHT(&apos;000&apos; || s.KCCR, 3) || &apos;-&apos; || RIGHT(&apos;0000&apos; || s.KCSZ, 4) AS ITEM,
        ///	s.KQTY AS UNITS,
        ///	h.IUPD AS UPC,
        ///	h.IDES AS Description,
        ///	h.IDPT As Department,
        ///	s.KCCL As Class,
        ///	s.KCVN As Vendor,
        ///	s.KCST as Style,
        ///	s.KCCR as Colour,
        ///	s.KCSZ as Size
        ///FROM
        ///	IPISETS s
        ///		JOIN IPITHDR h
        ///			ON h.ICLS = s.KCCL
        ///			AND h.IVEN = s.KCVN
        ///			AND h.ISTY = s.KCST
        ///			AND h.ICLR = s.KCCR
        ///			AND  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLPackItemGetPackDetails {
            get {
                return ResourceManager.GetString("SQLPackItemGetPackDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	m.DCTR as Market,
        ///	s.SSTR as Store,
        ///	s.SNAM as StoreName,
        ///	&apos;999&apos; as StoreGrade,
        ///	0 as ReleaseQty,
        ///	CASE WHEN i.IAUPC IS NULL THEN 0 ELSE 1 END as Allocated,
        ///	CASE WHEN z.IAUPC IS NULL THEN 0 ELSE 1 END as Locked
        ///
        ///FROM 
        ///	IPSTORE s
        ///	JOIN DSSTORE m
        ///		ON m.DSTR = s.SSTR  
        ///
        ///	LEFT JOIN DSAPPALC i
        ///		ON i.IASTR=s.SSTR 
        ///		AND i.IASTS = &apos;P&apos; 
        ///		AND i.IAORIGIN=&apos;S&apos; 
        ///		AND i.IACLS = &lt;class&gt;
        ///		AND i.IAVEN= &lt;vendor&gt;
        ///		AND i.IASTY= &lt;style&gt;
        ///		AND i.IACLR= &lt;colour&gt;
        ///		AND i.IASIZ= &lt;size&gt;
        ///
        ///	LEFT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLPackItemGetStowawayAllocations {
            get {
                return ResourceManager.GetString("SQLPackItemGetStowawayAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM
        ///	DSIALOK
        ///WHERE
        ///	IACLS = &lt;class&gt;
        ///	AND IAVEN = &lt;vendor&gt;
        ///	AND IASTY = &lt;style&gt;
        ///	AND IACLR = &lt;colour&gt;
        ///	AND IASIZ = &lt;size&gt;.
        /// </summary>
        internal static string SQLPackItemUnlock {
            get {
                return ResourceManager.GetString("SQLPackItemUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///	DSAPPALC 
        ///	(IASTS, IAORIGIN, IADEPT, IACLS,
        ///	 IAVEN, IASTY, IACLR, IASIZ, 
        ///	 IAUPC, IASTR, IASTRDSC, IAMKT, 
        ///	 IAGRADE, IASYSQTY, IARLSQTY, IARLSYN, 
        ///	 IASRRUNT, IARLSDAT, IARLSUSR)
        ///VALUES 
        ///	(&apos;&apos;, &apos;M&apos;, &lt;departmentId&gt;, &lt;class&gt;, 
        ///	&lt;vendor&gt;, &lt;style&gt;, &lt;colour&gt;, &lt;size&gt;, 
        ///	&apos;&lt;upc&gt;&apos;, &lt;store&gt;, &apos;&lt;storeName&gt;&apos;, &apos;&lt;market&gt;&apos;, 
        ///	&apos;&lt;storeGrade&gt;&apos;, 0, &lt;releaseQty&gt;, &apos;Y&apos;, 
        ///	0, &apos;&lt;dateTime&gt;&apos;, &apos;&lt;userName&gt;&apos;).
        /// </summary>
        internal static string SQLPackItemUpdateAllocations {
            get {
                return ResourceManager.GetString("SQLPackItemUpdateAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	h.ICLS As CLASS, 
        ///	h.IVEN AS VENDOR, 
        ///	h.ISTY AS STYLE, 
        ///	h.ICLR AS COLOUR, 
        ///	h.ISIZ AS SIZE, 
        ///	h.IUPD AS UPC
        ///FROM
        ///	IPITHDR h
        ///	JOIN IPISETS s
        ///	ON h.ICLS = s.KCLS
        ///	AND h.IVEN = s.KVEN
        ///	AND h.ISTY = s.KSTY
        ///	AND h.ICLR = s.KCLR
        ///	AND h.ISIZ = s.KSIZ
        ///WHERE
        ///	h.ISET = &apos;Y&apos;.
        /// </summary>
        internal static string SQLPackItemValidate {
            get {
                return ResourceManager.GetString("SQLPackItemValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	ds.DIDPT As Department,
        ///	ds.DICLS As Class,
        ///	ds.DIVEN As Vendor,
        ///	ds.DISTY As Style,
        ///	ds.DICLR As Colour,
        ///	ds.DISIZ As Size,
        ///	ip.IUPD As UPC,
        ///	ip.IDES As Description,
        ///	ip.IMLT As MinDistLot,
        ///	ds.DMDQT as MinDispQty
        ///
        ///FROM
        ///	DSITHDR ds
        ///	JOIN IPITHDR ip
        ///	ON ds.DICLS = ip.ICLS
        ///	AND ds.DIVEN = ip.IVEN
        ///	AND ds.DISTY = ip.ISTY
        ///	AND ds.DICLR = ip.ICLR
        ///	AND ds.DISIZ = ip.ISIZ
        ///
        ///&lt;whereClause&gt;
        ///
        ///ORDER BY
        ///	ds.DIDPT,
        ///	ds.DICLS,
        ///	ds.DIVEN,
        ///	ds.DISTY,
        ///	ds.DICLR,
        ///	ds.DISIZ.
        /// </summary>
        internal static string SQLStockInfoSelect {
            get {
                return ResourceManager.GetString("SQLStockInfoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM DSSRSTD1 WHERE SDLSTR = &lt;storeId&gt;.
        /// </summary>
        internal static string SQLStoreDeleteScheduleDelete {
            get {
                return ResourceManager.GetString("SQLStoreDeleteScheduleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT        ///	SDLSTS as Status,        ///	SDLSTR as StoreId,        ///	SDLDDAT as ScheduleDate,        ///	SDLUSR as NetworkId,        ///	SDLRDAT as LastUpdated,        ///	0 As DELETEFLAG,        ///	SDLSTR as OldStoreId        ///FROM        ///	DSSRSTD1        ///WHERE         ///	SDLSTS IN (&lt;statusList&gt;)        ///ORDER BY        ///	SDLSTS,        ///	SDLDDAT.
        /// </summary>
        internal static string SQLStoreDeleteScheduleSelect {
            get {
                return ResourceManager.GetString("SQLStoreDeleteScheduleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///	DSSRSGR
        ///SET
        ///	GDGRADE = P_GDGRADE,
        ///	GDGNAM = P_GDGNAM,
        ///	GDCHGU = P_GDCHGU,
        ///	GDCHGD = P_GDCHGD
        ///WHERE
        ///	GDSTR = P_GDSTR.
        /// </summary>
        internal static string SQLStoreGradeUpdate {
            get {
                return ResourceManager.GetString("SQLStoreGradeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	SUBSTRING(m.SKEY, 2) as Id,
        ///	m.SNAM AS Description,
        ///	s.SGPCHU as ChangedBy,
        ///	s.SGPCHD as ChangedDate,
        ///	CASE WHEN s.SGPID IS NULL THEN 0 ELSE 1 END As Selected
        ///FROM
        ///	IPSTRTB m
        ///	LEFT JOIN DSSRSGP s
        ///		ON SUBSTRING(m.SKEY, 2) = s.SGPID
        ///WHERE
        ///	m.SKEY LIKE &apos;U%&apos;
        ///ORDER BY
        ///	m.SKEY
        ///.
        /// </summary>
        internal static string SQLStoreGroupsSelect {
            get {
                return ResourceManager.GetString("SQLStoreGroupsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	ds.DCTR As CountryId,
        ///	c.CSDESC As Country,
        ///	s.SSTR As StoreId,
        ///	s.SNAM As StoreName,
        ///	ds.DLEADT as LeadTime
        ///
        ///FROM
        ///	IPSTORE s
        ///	JOIN DSSTORE ds
        ///	ON s.SSTR = ds.DSTR
        ///
        ///	JOIN DSCNTAP c
        ///	ON ds.DCTR = c.CSCODE
        ///
        ///WHERE
        ///	s.SSTS IN (&apos;S&apos;, &apos;F&apos;)
        ///.
        /// </summary>
        internal static string SQLStoreLeadTimesSelect {
            get {
                return ResourceManager.GetString("SQLStoreLeadTimesSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DSSTORE SET DLEADT = &lt;leadTime&gt; WHERE DSTR = &lt;storeId&gt;.
        /// </summary>
        internal static string SQLStoreLeadTimesUpdate {
            get {
                return ResourceManager.GetString("SQLStoreLeadTimesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///SWKEY   as HierarchyKey,
        ///SWDEPT  as Department,
        ///SWCLS   as Class,
        ///SWMKT   as Market,
        ///SWMKTC  as MarketColour,
        ///IFNULL(CSCSEQ, &apos;0&apos;) as MarketSequence,
        ///SWGRD   as Grade,
        ///SWGRDN  as GradeDescription,
        ///SWSTR   as Store,
        ///SWSTRN  as StoreName,
        ///SWKYVL  as KeyValue,
        ///
        ///	CASE 
        ///	WHEN SWSTRTYP = &apos;C&apos; THEN &apos;Online&apos; 
        ///	WHEN SWSTRTYP = &apos;B&apos; THEN &apos;B&amp;M&apos; 
        ///	ELSE &apos;Unknown&apos; END as StoreType,
        ///
        ///	CASE
        ///	WHEN SWWBTYP =&apos;D&apos; THEN &apos;Daily&apos;
        ///	WHEN SWWBTYP =&apos;W&apos; THEN &apos;Weekly&apos;
        ///	ELSE &apos;Unknown&apos; END As WorkBench,
        ///
        /// 
        ///SWFF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLSummaryWorkbench {
            get {
                return ResourceManager.GetString("SQLSummaryWorkbench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE ALIAS DSSRSWB&lt;alias&gt; FOR DSSRSWB(&lt;member&gt;).
        /// </summary>
        internal static string SQLSummaryWorkbenchAliasCreate {
            get {
                return ResourceManager.GetString("SQLSummaryWorkbenchAliasCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP ALIAS DSSRSWB&lt;alias&gt;.
        /// </summary>
        internal static string SQLSummaryWorkbenchAliasDrop {
            get {
                return ResourceManager.GetString("SQLSummaryWorkbenchAliasDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM DSSRSWB&lt;member&gt; WHERE SWDEPT = &lt;departmentId&gt;.
        /// </summary>
        internal static string SQLSummaryWorkbenchDelete {
            get {
                return ResourceManager.GetString("SQLSummaryWorkbenchDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	MGKEY as MessageId,
        ///	MGSYSN as SystemTag,
        ///	MGUSER as NetworkId,
        ///	MGSTRT as StartTime,
        ///	MGENDT as EndTime,
        ///	MGMON as Mon,
        ///	MGTUE as Tue,
        ///	MGWED as Wed,
        ///	MGTHU as Thu,
        ///	MGFRI as Fri,
        ///	MGSAT as Sat,
        ///	MGSUN as Sun,
        ///	MGMSG as Message,
        ///	MGSTS as Active,
        ///	MGTRM as Terminate
        ///FROM 
        ///	DSSRSMSG
        ///
        ///WHERE
        ///	MGSTS = &apos;1&apos;
        ///	AND (MGUSER = &apos;*ALL&apos; OR MGUSER = &apos;&lt;networkId&gt;&apos;)
        ///	AND (MGSYSN = &apos;*ALL&apos; OR MGSYSN in (&apos;&lt;systemTags&gt;&apos;))
        ///	AND (MGSTRT=0 OR &lt;time&gt; BETWEEN MGSTRT AND MGENDT)
        ///	AND SUBSTR(MGSUN ||  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLSystemMessagesSelect {
            get {
                return ResourceManager.GetString("SQLSystemMessagesSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	d.DDPT as Id,
        ///	RTRIM(d.DNAM) || &apos; (&apos; || d.DDPT || &apos;)&apos; as Department
        ///FROM
        ///	DSUSRDA ud
        ///	JOIN IPDEPTS d
        ///	ON d.DDPT = ud.USDEPT
        ///WHERE
        ///	&lt;whereClause&gt;	
        ///ORDER BY
        ///	d.DNAM.
        /// </summary>
        internal static string SQLUserDeptAssignedDepts {
            get {
                return ResourceManager.GetString("SQLUserDeptAssignedDepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	d.DDPT as Id,
        ///	RTRIM(d.DNAM) || &apos; (&apos; || d.DDPT || &apos;)&apos; as Department
        ///FROM
        ///	IPDEPTS d
        ///WHERE
        ///	d.DDPT NOT IN (SELECT USDEPT FROM DSUSRDA WHERE &lt;whereClause&gt;)
        ///ORDER BY
        ///	d.DNAM.
        /// </summary>
        internal static string SQLUserDeptAvailableDepts {
            get {
                return ResourceManager.GetString("SQLUserDeptAvailableDepts", resourceCulture);
            }
        }
    }
}
